/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.projectlombok:lombok:1.18.28")
    api("com.google.code.gson:gson:2.10.1")
    api("commons-io:commons-io:2.15.0")
}

group = "xyz.hlafaille.espresso"
version = "1.0-SNAPSHOT"
description = "buildwithespresso"
java.sourceCompatibility = JavaVersion.VERSION_17
